### PR TITLE
Login Screen added,

### LINKED ISSUE #5: feature#4-LoginScreen
# REQUIREMENTS
As a user, I want to have access to the login form using the following data:

* Email 
* Password
* Also, the form must provide an alternative way to log in with a Google account.

# DESIGN
imagen

### PR DESCRIPTION
**Pull request by TonyHdez-Pi**
Co-authored-by: TonyHdez-Pi <tonyhdezpi@gmail.com>

# Description
Create a Login screen

  ## Screenshots 
imagen

### CODE REVIEW

**Review by AmarilloVel — CHANGES_REQUESTED** [review]
Change the title property of the buttonComponents

**Review by AmarilloVel — APPROVED** [review]
Nicee

**Review by Astroyayo — APPROVED** [review]
Approved from the all mighty

**Review by Ch4s3d — APPROVED** [review]
Delightful 🥇

**Pull request merged**
